name: small-pipeline-workflow

on: push

jobs:
  build-and-test:
    # Specify OS environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.6.0'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install jest

      # Step 4: Run tests or another script
      - name: Run Tests
        run: npm test
